version: '3.8'

services:
  nextjs-app:
    container_name: nextjs-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/app:/usr/src/app
    environment:
      - NODE_ENV=production
