version: '3.8'

services:
  med-cert-app-prod:
    container_name: MC-production
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/app:/usr/src/app
    environment:
      - NODE_ENV=production
